; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4CC917F4-6535-412A-93EE-9D849FA437D0}
AppName=VisCord
AppVersion=1.4.1.0
AppVerName=VisCord 1.4.1.0
AppPublisher=WindowsLogic Productions
AppPublisherURL=http://www.windowslogic.co.uk/
AppSupportURL=http://www.windowslogic.co.uk/
AppUpdatesURL=http://www.windowslogic.co.uk/
DefaultDirName=C:\VisCord
DisableProgramGroupPage=yes
DisableDirPage=no
LicenseFile=J:\Projects\EULA.txt
InfoBeforeFile=J:\Projects\Warning Installer Theft.txt
InfoAfterFile=J:\Projects\Thanks.txt
OutputDir=J:/Projects/Output
OutputBaseFilename=VisCord Legacy Setup
SetupIconFile=J:\Projects\VisCord\VisCord\Discord.ico
WizardImageFile=J:\Projects\SetupImage.bmp
WizardSmallImageFile=J:\Projects\VisCord.bmp
DisableWelcomePage=no
Compression=lzma2
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "J:\Projects\VisCord\VisCord\bin\x64\Release\*"; Excludes: "*.ini, *.config, *.pdb, *.xml"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\VisCord"; Filename: "{app}\VisCord.exe"
Name: "{commondesktop}\VisCord"; Filename: "{app}\VisCord.exe"; Tasks: desktopicon

